version: '3'
services:
  redis:
    image: redis:latest
    networks:
      - default
    ports:
      - "6379:6379"

  timedb:
    image: timescale/timescaledb:latest-pg10
    ports:
      - "5432:5432"
    volumes:
      - timedb-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=oasishub
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  migrate:
    image: migrate/migrate
    volumes:
      - ./db/timescale/migrations:/migrations
    command: version
    entrypoint:
      - migrate
      - -path
      - /migrations/
      - -database
      - postgres://postgres:password@timedb:5432/oasishub?sslmode=disable

  server:
    container_name: oasishub-indexer-server
    build: .
    ports:
      - "8081:8081"
    environment:
      - NODE_URL=http://host.docker.internal:8080
      - GIN_MODE=release
      - DB_HOST=timedb
      - DB_NAME=oasishub
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on:
      - timedb

  job:
    container_name: oasishub-indexer-job
    build: .
    entrypoint: /go/bin/job
    environment:
      - NODE_URL=http://host.docker.internal:8080
      - DB_HOST=timedb
      - DB_NAME=oasishub
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on:
      - timedb

volumes:
  timedb-data:
