apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: job
  template:
    metadata:
      labels:
        component: job
    spec:
      containers:
        - name: job
          image: eu.gcr.io/job:v0.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: timescale-cluster-ip-service
            - name: DB_NAME
              value: oasishub
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
            - name: ROLLBAR_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: rollbaraccesstoken
                  key: ROLLBARACCESSTOKEN
