apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: eu.gcr.io/server:v0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: GIN_MODE
              value: production
            - name: DB_HOST
              value: timescale-cluster-ip-service
            - name: DB_NAME
              value: oasishub
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
            - name: ROLLBAR_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: rollbaraccesstoken
                  key: ROLLBARACCESSTOKEN
